### ISSUE TITLE
Private repository - 'Not found'

### ISSUE THREAD

**Issue by aand18** [GitZip/chrome-extension#1]
It doesn't download from a private repo:

> Collect checked items...
> Collect blob urls...
> .gitignore url fetched.
> LICENSE url fetched.
> NOTICE url fetched.
> README.txt url fetched.
> build.sh url fetched.
> Not Found

I have the private token.

**Comment by KinoLien** [comment]
Sorry for the late reply.

I tried to reproduce on my private repo, but still work..
Could you tell me what type of the file?

Or maybe I should skip the "Not Found" error and just zip the found files?

**Comment by aand18** [comment]
I've tried it now on a single file:

> Progress Dashboard
Collect checked items...
Collect blob urls...
LICENSE.txt url fetched.
Collect blob contents...
Not Found

On a single folder:
> Progress Dashboard
Collect checked items...
Collect blob urls...
Not Found

I'm not sure what it doesn't find...

**Comment by KinoLien** [comment]
I had faced same situation,
I just got private token again, and then problem solved.

I would add the handler in next version.
